# Site Settings
title:               Mike Psaris
tagline:             
description:        A personal website of Mike Psaris
baseurl:            #"/blog"
url:                #"https://mikepsaris.github.io"
github:
  url:               #"https://mikepsaris.github.io/blog"
author:
  name:              "Mike Psaris"
  email:             "mike.psaris@gmail.com"
  twitter:           "mikepsaris"
  instagram:         "mikepsaris"
  github:            "mikepsaris"
  facebook:          "mike.psaris"
  linkedin:          "mikepsaris"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

theme: jekyll-theme-minimal
